### ISSUE TITLE
Addon-agent container with image tag latest instead of fixed version

### ISSUE THREAD

**Issue by rtrive** [open-cluster-management-io/cluster-proxy#114]
Hi Guys!

I've a problem with the `addon-agent` container that has a wrong image with the tag latest instead of a fixed version. I check the code and it seems all right but unfortunately, when I deploy the cluster-proxy on a managed cluster the containers of deployment have these values:

```yaml
containers:
      - args:
        - --proxy-server-host=127.0.0.1
        - --proxy-server-port=8091
        - --agent-identifiers=host=dev&host=dev.open-cluster-management-cluster-proxy&host=dev.open-cluster-management-cluster-proxy.svc.cluster.local
        - --ca-cert=/etc/ca/ca.crt
        - --agent-cert=/etc/tls/tls.crt
        - --agent-key=/etc/tls/tls.key
        command:
        - /proxy-agent
        image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
        imagePullPolicy: IfNotPresent
        name: proxy-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ca
          name: ca
          readOnly: true
        - mountPath: /etc/tls
          name: hub
          readOnly: true
      - args:
        - --v=2
        - --hub-kubeconfig=/etc/kubeconfig/kubeconfig
        - --cluster-name=dev
        - --proxy-server-namespace=open-cluster-management-addon
        - --enable-port-forward-proxy=true
        command:
        - /agent
        image: quay.io/open-cluster-management/cluster-proxy:latest
        imagePullPolicy: IfNotPresent
        name: addon-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubeconfig/
          name: hub-kubeconfig
          readOnly: true
```

as you can see the `proxy-agent` container has version `v0.2.0` instead the `addon-agent` has the latest version that is causing crashloopbackoff errors. 
Why they don't have the same version? I'll attach also the ManagedProxy configuration

```yaml
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    dump:
      secrets:
        signingAgentServerSecretName: agent-server
        signingProxyClientSecretName: proxy-client
        signingProxyServerSecretName: proxy-server
    signer:
      type: SelfSigned
  proxyAgent:
    image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
    replicas: 3
  proxyServer:
    entrypoint:
      port: 8091
      type: PortForward
    image: quay.io/open-cluster-management/cluster-proxy:v0.2.0
    inClusterServiceName: proxy-entrypoint
    namespace: open-cluster-management-addon
    replicas: 3
```

Thanks!
