### ISSUE TITLE
Support access not only kube-apiserver but also other services in the managed cluster

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/cluster-proxy#53]
Is it possible for cluster-proxy to support the above feature?

Currently, proxy-agent would direct all traffic into kube-apiserver through this ExternalName type service:

https://github.com/open-cluster-management-io/cluster-proxy/blob/c83c9c28fbd0ae10b751013233ad592a77f0bc48/pkg/proxyagent/agent/agent.go#L447-L463

But if we do the following:
1. Add the target service' hostname in proxy-agent  "agent-identifiers" flag. It can make sure requests will go to the desired managed cluster through the tunnel.
2. Add another ExternalName service to point to the target service.

Therefore another target service on the managed cluster could be accessed by the user on the hub as well.

**Comment by showeimer** [comment]
Hi @yue994488!  Would you be able to evaluate the technical feasability of this enhancement request, use case, and how much work it may be?

**Comment by xuezhaojun** [comment]
I have a draft idea about this, we can add a "map" struct `services` in `managedproxyconfigurations`:

```yaml
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  services: # Here!! This is what we need to add.
    search: search.namespace.svc
    ui: ui.namespace.svc
  authentication:
    dump:
      secrets: {}
    signer:
      type: SelfSigned
  proxyServer:
    image: quay.io/open-cluster-managment.io/cluster-proxy:latest
    ...
```
The key represents the service we want to access, and the value is the respective service address.

The agent will generate several ExternalName Services based on this map structure.

And also register on proxy-agent with more agent-identifiers:
* cluster1-search
* cluster1-ui

And user can use `cluster1-search` as the hostname of the request to access the search service on the agent(managed cluster).

Is this making sense? Please share more advice, thanks!

**Comment by qiujian16** [comment]
FYI @yue9944882 this is case that we discussed today.

**Comment by qiujian16** [comment]
@xuezhaojun I do not think it could be a cluster scoped configuration. I wonder this should be a per cluster or per clusterset configuration. Also it is not quite formal to use `cluster1-search` as the hostname. It probably could be `search.default.cluster.cluster1`

**Comment by xuezhaojun** [comment]
Agree

**Comment by yue9944882** [comment]
in the current implementation, we have an implicit hostname resolver from `<cluster name>` to "kubernetes.default" in each cluster which is working by applying an `ExternalName` type service. it makes sense to allow more extended resolvers in our addon. how about we add the following extensions to the configuration:

```
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  serviceResolvers:
  - hostnameTemplate: "$cluster"
     namespace: default
     name: kubernetes
  - hostnameTemplate: "mySvc.$cluster"
     namespace: default
     name: my-svc
    ...
```

**Comment by xuezhaojun** [comment]
> in the current implementation, we have an implicit hostname resolver from `<cluster name>` to "kubernetes.default" in each cluster which is working by applying an `ExternalName` type service. it makes sense to allow more extended resolvers in our addon. how about we add the following extensions to the configuration:
> 
> ```
> apiVersion: proxy.open-cluster-management.io/v1alpha1
> kind: ManagedProxyConfiguration
> metadata:
>   name: cluster-proxy
> spec:
>   serviceResolvers:
>   - hostnameTemplate: "$cluster"
>      namespace: default
>      name: kubernetes
>   - hostnameTemplate: "mySvc.$cluster"
>      namespace: default
>      name: my-svc
>     ...
> ```

Should  I implement a prototype based on this design?

**Comment by yue9944882** [comment]
@xuezhaojun that would be really helpful, thanks!

**Comment by xuezhaojun** [comment]
> @xuezhaojun I do not think it could be a cluster scoped configuration. I wonder this should be a per cluster or per clusterset configuration. Also it is not quite formal to use `cluster1-search` as the hostname. It probably could be `search.default.cluster.cluster1`

I not sure about if should be "per cluster" configuration. Could you explain more about the advantage to configrate in this way?

**Comment by qiujian16** [comment]
The issue is who should be able to set what service to access on spoke. Let's say a user who only can access clusterA and the user wants to set a service on proxy, he/she cannot set this because it needs the permission to update this cluster-scoped configuration.

**Comment by xuezhaojun** [comment]
> The issue is who should be able to set what service to access on spoke. Let's say a user who only can access clusterA and the user wants to set a service on proxy, he/she cannot set this because it needs the permission to update this cluster-scoped configuration.

I see, that means we assuming user who can access clusterA also have the permission to "enable" other services on clusterA accessible via cluster-proxy.

**Comment by xuezhaojun** [comment]
In other words, it also make sense if it is cluster-scoped. Because the proxy-server itself is cluster-scoped. Even if user only set serviceA on clusterA, but it still is a change to every user.  Even if they can not pass the auth check, but still they can send requests to this new service host.

**Comment by xuezhaojun** [comment]
And another issue is, user who want to access ServiceA on clusterA, may not need to access kube-apiserver on ClusterA.

**Comment by xuezhaojun** [comment]
> @xuezhaojun I do not think it could be a cluster scoped configuration. I wonder this should be a per cluster or per clusterset configuration. **Also it is not quite formal to use `cluster1-search` as the hostname. It probably could be `search.default.cluster.cluster1`**

I found another issue: if the hostname be `search.default.cluster.cluster1` the this host must represent an ExternalName service in cluster1. But we can have dot in Service name so, we can set hostname to `search.default.cluster.cluster1`.

**Comment by qiujian16** [comment]
> And another issue is, user who want to access ServiceA on clusterA, may not need to access kube-apiserver on ClusterA.

I think it is fine. We do not have a fine grained rbac for different services on spoke. A user is supposed to be the admin of clusterA.

**Comment by xuezhaojun** [comment]
> And another issue is, user who want to access ServiceA on clusterA, may not need to access kube-apiserver on ClusterA.

I got an idea to deal with this.

1. Create a namespace called "cluster1" on the managed cluster "cluster1".
2. Create a ExternalName Service "search" (for example) in cluster1 namespace. And the `externalName` field of this Service is point to `search.default.svc` (say the search server is deployed in the default namespace)
3. Now the user could use hostname `search.cluster1` to access this service.

**Comment by qiujian16** [comment]
what if you have two service with the same name but in different ns on spoke?

**Comment by xuezhaojun** [comment]
> what if you have two service with the same name but in different ns on spoke?

That would require a map with customized names, such as `search1` for `search` in `namespace1`,  `search2` for `search` in `namespace2`.

**Comment by xuezhaojun** [comment]
Currently, we are using the ExternalName to map `cluster name` to `kubernetes.default.svc`. 

But with this mode, we can not forward a hostname like `serviceA.namespceA.clusterA` to the target service we want.

Recently, I tried to use `coredns` to replace the ExternalName service with the hostname mapping work.

To do this, we need to run a `coredns` server as sidebar in the same pod of the `proxy-agent`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.agentDeploymentName }}
  annotations:
  {{- with .Values.agentDeploymentAnnotations }}
  {{ toYaml . | indent 8 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: cluster-proxy
      proxy.open-cluster-management.io/component-name: proxy-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
      {{- with .Values.agentDeploymentAnnotations }}
      {{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        open-cluster-management.io/addon: cluster-proxy
        proxy.open-cluster-management.io/component-name: proxy-agent
    spec:
      serviceAccount: cluster-proxy
      containers:
        - name: proxy-agent
          image: {{ .Values.proxyAgentImage }}
          imagePullPolicy: IfNotPresent
          command:
            - /proxy-agent
          args:
            - --proxy-server-host={{ .Values.serviceEntryPoint }}
            - --proxy-server-port={{ .Values.serviceEntryPointPort }}
            - --agent-identifiers={{ list (printf "host=%s" .Values.clusterName) (printf "host=%s.%s" .Values.clusterName .Release.Namespace) (printf "host=%s.%s.%s" .Values.clusterName .Release.Namespace .Values.serviceDomain) | join "&" }}
            - --ca-cert=/etc/ca/ca.crt
            - --agent-cert=/etc/tls/tls.crt
            - --agent-key=/etc/tls/tls.key
            {{- range .Values.additionalProxyAgentArgs }}
            - {{ . }}
            {{- end }}
          volumeMounts:
            - name: ca
              mountPath: /etc/ca
              readOnly: true
            - name: hub
              mountPath: /etc/tls
              readOnly: true
          lifecycle:
            postStart: # !!! We edit the /etc/resolv.config when pod is start
              exec:
                command: ["/bin/sh", "-c", "echo \"$(sed \'1i nameserver 127.0.0.1\' /etc/resolv.conf)\" > /etc/resolv.conf"]
        - name: addon-agent
          image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /agent
          args:
            - --v=2
            {{- range .Values.addonAgentArgs }}
            - {{ . }}
            {{- end }}
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/kubeconfig/
              readOnly: true
        - name: dns-override # !!! We add a new container and run it as root user
          securityContext:
            runAsUser: 0
          image: registry.cn-hangzhou.aliyuncs.com/acs/coredns:1.6.2
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
              readOnly: true
      volumes:
        - name: ca
          secret:
            secretName: cluster-proxy-ca
        - name: hub
          secret:
            secretName: cluster-proxy-open-cluster-management.io-proxy-agent-signer-client-cert
        - name: hub-kubeconfig
          secret:
            secretName: cluster-proxy-hub-kubeconfig
        - name: config-volume # !!! We Add a configmap here
          configMap:
            name: cluster-proxy-dns-override
            items:
            - key: Corefile
              path: Corefile
```

The configmap should be:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-proxy-dns-override
  namespace: {{ .Release.Namespace }}
data:
  Corefile: |
    .:53 {
      errors
      log
      rewrite name local-cluster kubernetes.default.{{ .Values.serviceDomain }}
      rewrite name local-cluster.open-cluster-management-cluster-proxy kubernetes.default.{{ .Values.serviceDomain }}
      rewrite name local-cluster.open-cluster-management-cluster-proxy.svc.cluster.local kubernetes.default.{{ .Values.serviceDomain }}
      forward . /etc/resolv.conf
      cache 30
      reload
    }
```

---

Two defects of this approach are:
1. We need to run as root to expose DNS on port `53`, it could cause security issues on some platforms.
2. We need to provide another `coredns` image.
