### ISSUE TITLE
Proxy-Agent support customize `proxy-server-port`

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/cluster-proxy#74]
I found the `proxy-agent` can set a customize port, so it use `8091` in default.

In my case,  I'm using `type: Hostname` as entrypoint type, and also using `443` port to expose the proxy-server.

So could we add a flag to support user to specify the `--proxy-server-port` in `proxy-agent`?

PS: 
It's a simple issue, and I think the only thing we should have a discussion about is the flags' name.
Should it be as the following?

```yaml
    proxyServer:
    image: {{ .Values.proxyServerImage }}
    namespace: {{ .Release.Namespace }}
    entrypoint:
      {{- if .Values.proxyServer.entrypointAddress }}
      type: Hostname
      hostname:
        value: {{ .Values.proxyServer.entrypointAddress }}
        port: {{ ..Values.proxyServer.entrypointPort }} # Here!! Updated
      {{- else if .Values.entrypointLoadBalancer }}
      type: LoadBalancerService
      loadBalancerService: {}
      {{- else  }}
      type: PortForward
      {{- end }}
```

agent.go add a flag: 
```go
serviceEntryPointPort = proxyConfig.Spec.ProxyServer.Entrypoint.Hostname.Port
```

I also have free time to fix this issue. 😁
